fast: 
	iverilog blink_fast.v
	./a.out
	@echo "nao esqueca de ver o resultado: gtkwave dump.vcd"

visible:
	iverilog blink_visible.v
	./a.out
	@echo "nao esqueca de ver o resultado: gtkwave dump.vcd"
